### ISSUE TITLE
Execution of Scarb Benchmarking

### ISSUE THREAD

**Issue by neotheprogramist** [visoftsolutions/dojo#14]
**Related Main Issue:** [Benchmarking Dojo's Storage Efficiency in Terms of Gas Usage](https://github.com/visoftsolutions/dojo/issues/13)

### Objective

The primary objective of this sub-issue is to delve deeper into the benchmarking process using **Scarb**. We aim to:

1. Create a detailed procedure for executing benchmarks with the `scarb test` command.
2. Develop a mechanism to collect, interpret, and report the results from these benchmarks.

### Context

In line with our primary issue, which is focused on evaluating `Dojo's` storage efficiency, understanding the nuances of benchmarking with **Scarb** will play a pivotal role.

### Tasks

1. **Detailed Procedure for Scarb Benchmarking**: 
    - Investigate the functionalities and parameters offered by the `scarb test` command.
    - Draft a step-by-step guide, detailing the commands and options required to run benchmarks using Scarb.

2. **Gathering Benchmark Results**:
    - Define a structured format to capture benchmark results.
    - Automate the process of gathering and storing these results, if possible.

3. **Interpretation and Reporting**:
    - Identify key metrics to be derived from the benchmark results.
    - Propose a reporting format that is both comprehensive and easy to interpret.

### Expected Outcome

By the end of this sub-issue, we expect to have a well-defined method to perform benchmarks using **Scarb**, ensuring that the data obtained aligns with our broader objectives set in the main issue.

**Comment by matzayonc** [comment]
From my initial research:
- Scarb is designed for 'pure' cairo, and doesn't work well with dojo code out of the box, because of compiler extensions. `Sozo` is a wrapper used in `Dojo`.
- Even in dependcy Sozo [cairo-lang-test-runner](https://github.com/starkware-libs/cairo/blob/1937daaefed8653532f90348d9aadd1000ddbb73/crates/cairo-lang-test-runner/src/lib.rs#L77C55-L77C55) running tests always returns `Ok(None)`
- the most straight_forward solutions seems to be reading stdout directly `test dojo::world_test::test_entities ... ok (gas usage est.: 11552694)`, and extracting name, status (ok or not) and gas usage

**Comment by matzayonc** [comment]
One could use oneliner:
`cargo run -r --bin sozo -- --manifest-path crates/dojo-core/Scarb.toml test -f TEST_NAME | awk -F'[(|)]' '{gsub(/gas usage est.: /, "", $2); print $2}' | grep -vE '^$'`
 to get all the gas usages of TEST_NAME test, in dojo-core crate, with different suffixes.
Suffices could have complexity (TEST_NAME_SIMPLE) or numeric (TEST_NAME_22)
 
 Then results could be processed and shown as a result (average, minimum, maximum and standard deviation values)
