### ISSUE TITLE
Creating Benchmark Tests with Scarb and Katana

### ISSUE THREAD

**Issue by neotheprogramist** [visoftsolutions/dojo#16]
**Related Main Issue:** [Benchmarking Dojo's Storage Efficiency in Terms of Gas Usage](https://github.com/visoftsolutions/dojo/issues/13)

### Objective

The primary objective of this sub-issue is to craft and perform simple benchmark tests utilizing both **Scarb** and **Katana** for various storage scenarios to understand gas consumption.

### Context

In alignment with the main issue's focus on storage efficiency, utilizing our primary tools, **Scarb** and **Katana**, will offer valuable insights. Simple yet varied tests will provide a granular perspective on each storage scenario.

### Benchmark Tests

1. **Native Storage with Scarb and Katana**: 
    - Design and conduct a benchmark focusing on storage operations without any integration of Dojo.

2. **Simple Dojo Storage with Scarb and Katana**: 
    - Design a test that measures the performance of standard storage operations when Dojo is integrated.

3. **Dojo Packing Storage with Scarb and Katana**: 
    - Set up a benchmark to measure the efficacy and gas consumption of storage operations leveraging Dojo's packing feature.

4. **Dojo Indexing Storage with Scarb and Katana**: 
    - Create a test to assess the storage operations when using Dojo's indexing.

### Execution and Analysis

- For each benchmark test, execute them on both **Scarb** and **Katana**.
- Gather the results, ensuring accurate representation of gas consumption and efficiency for each storage scenario.
- Conduct a preliminary analysis, identifying any significant findings or patterns related to each scenario.

### Expected Outcome

Upon completion of this sub-issue, we anticipate a clear depiction of how each storage scenario performs in terms of gas consumption when benchmarked using **Scarb** and **Katana**. This data will be invaluable in directing further optimization and analysis endeavors.

**Comment by matzayonc** [comment]
Between `Scarb` and `Katana`, second options is better suited for benchmarking, as `Scarb` does not export gas usage outside  of `stdout`.

Proposed architecture
* Katana running locally (or remotely)
* Dojo contracts as test ground, because of compability with tooling and familiarity for developers
* `proptest` crate generating cases for property testing, failure persistence and regression (as well as async capabilities)
* Each contract is deployed, and called with data generated by proptest
* Fee is read from receipts

Resulting fee data for different calldata can be analized for base cost, complexity, minimum and maximum values, deviation and compared between implementations

**Comment by tarrencev** [comment]
This sounds good. Another approach that would be interesting is to try to calculate the specific steps for the storage operations. For example, `n` poseidon hashes, `m` storage reads, ... storage writes, steps, bitwise operations, etc.
